### PR TITLE
Added support for cameras

### PR DESCRIPTION
**Pull request by sibartlett**

### CODE REVIEW

**Comment by sibartlett** [comment]
According to the [API v2 documentation](http://docs.winkapiv2.apiary.io/#reference/device/camera), there are 3 modes (armed, disarmed and privacy). We're not currently handling privacy; I'm not sure which HomeKit state it should map to.

**Comment by thechrisreese** [comment]
I never dealt with Privacy because I was dealing with Canary which doesn't go along exactly with their API documentation. Canary changed their setting and Wink updated but never changed their API

**Comment by thechrisreese** [comment]
Canary has Privacy on or off but HomeKit doesn't have a setting for that. 

Canary also has home, away, night, or disabled. Those work as implemented here.

**Comment by sibartlett** [comment]
I imagine the modes may differ for Arlo or Nest Cam, so maybe it's best if we restrict the camera functionality to just Canary for now. Are you able to provide the whole JSON object for the Canary device, that's returned from the Wink API? You can redact sensitive information.

Also when we dis-arm the camera: is it correct to be setting "powered" attribute to false, rather than setting mode to "disabled" or "privacy"?

**Comment by thechrisreese** [comment]
Yes in my wink implementation I made a security.js for just Canary. We could go back to that and leave this with just motion alerts for cameras.

**Comment by thechrisreese** [comment]
Canary

{"uuid":"",

"desired_state":{"mode":"night","private":false},

"last_reading"{
1. "connection":true,
2. "connection_updated_at":1468040977.1555378,
3. "mode":"night",
4. "mode_updated_at":1480399280.7572448,
5. "private":false,"private_updated_at":1480399280.7572448,
6. "serial_number":"C100D1600978",
7. "serial_number_updated_at":1480399280.7572448,
8. "firmware_version":"v0.2.37",
9. "firmware_version_updated_at":1480399280.7572448,
10. "location_id":"215871",
11. "location_id_updated_at":1480399280.7572448,
12. "location_name":"Home",
13. "location_name_updated_at":1480399280.7572448,
14. "motion_true":null,
15. "motion_true_updated_at":null,
16. "desired_mode_updated_at":1475276933.208866,
17. "desired_private_updated_at":1468978065.6056201,
18. "mode_changed_at":1480399280.7572448},
19. "subscription":{"pubnub"{
    1. "subscribe_key":"",
    2. "channel":"camera-42926|ce8a4874cbd72b3e19d83626fad1e825162fd8b0|user-501698"}},
20. "camera_id":"42926",
21. "name":"Front Entry",
22. "locale":"en_us",
23. "units":{},
24. "created_at":1468040977,
25. "hidden_at":null,
26. "capabilities":{
    1. "fields"[{"type":"boolean", "field":"connection", "mutability":"read-only"}, 
    2. {"type":"string", "field":"mode", "choices": ["armed","disarmed","privacy"], "mutability":"read-write"},
    3. {"type":"string","field":"serial_number","mutability":"read-only"},
    4. {"type":"string","field":"firmware_version","mutability":"read-only"},
    5. {"type":"string","field":"location_id","mutability":"read-only"},
    6. {"type":"string","field":"location_name","mutability":"read-only"}],
27. "home_security_device":true},
28. "manufacturer_device_model":"canary",
29. "manufacturer_device_id":"0e8ed285da9b406d8f1e1e9e6c45700f",
30. "device_manufacturer":"canary",
31. "model_name":"Canary",
32. "upc_id":"371",
33. "upc_code":"canary",
34. "linked_service_id":"389073",
35. "lat_lng":[],
36. "location":""

**Comment by thechrisreese** [comment]
I would suggest using manufactur_device_model if possible to keep it as Canary only

**Comment by sibartlett** [comment]
I've updated this pull request. I decided to use `device_manufacturer`, as I think it might be safe to assume all Canary product(s) use the same modes.

**Comment by thechrisreese** [comment]
replaced the files and got here

 
[5/13/2017, 9:42:14 PM] [Wink] Initializing Wink platform...
/Users/reeseserver/.nvm/versions/node/v6.3.1/lib/node_modules/homebridge-wink3/dist/devices/.DS_Store:1
(function (exports, require, module, __filename, __dirname) { 
                                                              
SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /Users/reeseserver/.nvm/versions/node/v6.3.1/lib/node_modules/homebridge-wink3/node_modules/require-all/index.js:52:46
    at Array.forEach (native)

**Comment by sibartlett** [comment]
The files in the repository need to be compiled. I think the code is pretty good, so I'll merge the pull requests in, and publish a new version.

**Comment by sibartlett** [comment]
I've published `1.1.0` to NPM.

**Comment by thechrisreese** [comment]
updated. ill let you know how it goes.

**Pull request merged**
