### PR TITLE
Add Config.schema.json/ Update Dependencies

### PR DESCRIPTION
**Pull request by AppleTechy**
Changes included:
**1)** Add Config.schme.json 
-  Allows full configuration of the plugin via Config UI X
- Also created Changelog.md so that it will display in Config UI X if anyone goes to update the plugin through that.

**2)** Updated Dependencies
- Some dependencies had security advisories issued for them so went ahead and updated dependencies
-Used package-lock rather than yarn lock since I am not seeing any benefit of yarn over npm these days
- HAPI changed to publishing packages as scoped. So updated those dependencies

**3)** Bumped plugin version number from "2.1.0", to "2.1.1".

* I still have a Wink account but all of my devices have been moved to Hubitat so I was only able to test devices that can integrate into a Wink account. In my case Ecobee thermostats, sensors and Nest Protects. I saw no issues. For testing I was able to successfully authenticate to Wink and got it to register the accessories in homebridge just fine. Based off the limited changes made I am assuming it should function just fine

*With the announcement Wink made yesterday I am assuming this will probably be the last ever update needed.

### CODE REVIEW

**Comment by sibartlett** [comment]
I merged everything, except:

* the switch to package-lock.json
* the changelog file
* the change to .gitignore

I may merge them in later... but I spent a fair bit of time cleaning the commits up, and wanted to get a new version published ASAP.

New package is published as `3.0.0` - as I had to drop support for node 8.

**Comment by AppleTechy** [comment]
Sounds good. I just use npm rather than yarn. So that auto generated. Had to modify the git ignore otherwise it would have tried uploading that macOS hidden folder from my MBP. 
I would recommend the changelog.md even if it only starts with an entry for the latest update. The changelog md is more inline with the latest expectation of Homebridge plugins.
Glad you were able to sort through the PR.
*sorry if the formatting on this comment is a little weird, I’m writing on the GitHub mobile app.

**Comment by sibartlett** [comment]
Yeah, I will try to add the changelog... just I wanted to go to bed, and I been looking at this stuff for a while... 😄 

I might also update the .gitignore file too... tip: you can add a [global .gitignore](https://help.github.com/en/github/using-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer)

**Comment by AppleTechy** [comment]
Oh thanks for the tip regarding the global gitignore. Is there any reason I can't go ahead and delete my fork?

**Comment by AppleTechy** [comment]
Also I know you don't want to maintain. We created a homebridge-plugins repository to house no longer maintained plugins if you want to transfer ownership to that org. We can host it till someone else comes along and decides to maintain it. While adding you to still have access to the repo if you so decide you want to do something with it.

**Pull request closed without merging**
